import React, { useState, useEffect, useMemo } from 'react';

import { 
  AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, 
  PieChart, Pie, Cell, BarChart, Bar, LineChart, Line, Legend
} from 'recharts';
import { cn, formatCompactNumber, getSellThroughRate, getProductMovementSpeed } from '../../lib/utils';
import { ABCAnalysisSection } from './ABCAnalysisSection';
import { SKUMovementDashboard } from './SKUMovementDashboard';
import { 
  calculateStockTurnover, 
  calculateMonthlyTurnoverTrend, 
  getDateRangeForPeriod, 
  TimePeriod 
} from '../../lib/stockTurnoverService';
import { 
  calculateComprehensiveAnalytics 
} from '../../lib/comprehensiveAnalyticsService';
import { BusinessOwnerKPISection } from './analytics/BusinessOwnerKPISection';
import { ActionableInsightsSection } from './analytics/ActionableInsightsSection';
import { SalesPerformanceTrend } from './analytics/SalesPerformanceTrend';
import { TopProductsAnalytics } from './analytics/TopProductsAnalytics';
import { InventoryHealthOverview } from './analytics/InventoryHealthOverview';
import { ReorderStockoutIntelligence } from './analytics/ReorderStockoutIntelligence';
import { SellThroughAndFillRateSection } from './analytics/SellThroughAndFillRateSection';
import { TiedUpCapitalSection } from './analytics/TiedUpCapitalSection';
import { 
  TrendingUp, DollarSign, Package, BarChart3, Calendar, RotateCcw, FileDown, 
  Activity, MousePointer2, Clock, Ban, ChevronDown, CheckCircle2, ShieldCheck, 
  AlertTriangle, RefreshCw, Sparkles, HelpCircle, ArrowRight, UserCheck, Inbox,
  CornerDownRight, Database, ListFilter, AlertCircle, Printer, Download,
  FileSpreadsheet, FileText, Check, X, ExternalLink
} from 'lucide-react';
import { 
  collection, query, where, onSnapshot, doc, setDoc, updateDoc, getDocs, writeBatch 
} from 'firebase/firestore';
import { db } from '../../lib/firebase';
import { useAuth } from '../../contexts/AuthContext';
import { useSettings } from '../../contexts/SettingsContext';
import { motion, AnimatePresence } from 'motion/react';
import { InsightBadge } from '../common/InsightBadge';

const COLORS = ['#3b82f6', '#0ea5e9', '#10b981', '#f59e0b', '#f43f5e', '#64748b'];

interface AnalyticsProps {
  defaultTab?: string;
}

export function Analytics({ defaultTab }: AnalyticsProps = {}) {
  const { user } = useAuth();
  const { profile, company, currency } = useSettings();
  const [products, setProducts] = useState<any[]>([]);
  const [stockMovements, setStockMovements] = useState<any[]>([]);
  const [invoices, setInvoices] = useState<any[]>([]);
  const [productsLoaded, setProductsLoaded] = useState(false);
  const [movementsLoaded, setMovementsLoaded] = useState(false);
  const [invoicesLoaded, setInvoicesLoaded] = useState(false);

  // Filter States
  const [selectedPeriod, setSelectedPeriod] = useState<TimePeriod>('This Month');
  const [customStartDate, setCustomStartDate] = useState<string>('');
  const [customEndDate, setCustomEndDate] = useState<string>('');
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('All');

  // Export Modal & Feedback State
  const [showExportModal, setShowExportModal] = useState(false);
  const [exportFeedback, setExportFeedback] = useState<string | null>(null);

  const showToast = (msg: string) => {
    setExportFeedback(msg);
    setTimeout(() => setExportFeedback(null), 4000);
  };

  const downloadFile = (content: string, filename: string, mimeType: string) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleExportExecutiveSummaryCSV = () => {
    const dateStr = new Date().toISOString().split('T')[0];
    const companyName = company?.name || 'Invenio Workspace';
    
    let csv = `INVENIO EXECUTIVE INVENTORY & FINANCIAL ANALYTICS REPORT\n`;
    csv += `Organization,${companyName}\n`;
    csv += `Reporting Period,${selectedPeriod}\n`;
    csv += `Currency,${currency}\n`;
    csv += `Generated Date,${new Date().toLocaleString()}\n`;
    csv += `Generated By,${profile?.name || user?.email || 'User'}\n\n`;

    csv += `EXECUTIVE FINANCIAL & OPERATIONAL KPIS\n`;
    csv += `Metric,Value,Unit\n`;
    csv += `Total Revenue,${comprehensiveAnalytics.revenue.toFixed(2)},${currency}\n`;
    csv += `Cost of Goods Sold (COGS),${comprehensiveAnalytics.cogs.toFixed(2)},${currency}\n`;
    csv += `Gross Profit,${comprehensiveAnalytics.grossProfit.toFixed(2)},${currency}\n`;
    csv += `Gross Margin,${comprehensiveAnalytics.grossProfitMargin.toFixed(1)},%\n`;
    csv += `Estimated Net Profit,${comprehensiveAnalytics.netProfit.toFixed(2)},${currency}\n`;
    csv += `Operating Profit Margin,${comprehensiveAnalytics.operatingProfitMargin.toFixed(1)},%\n`;
    csv += `Total Inventory Holding Value,${comprehensiveAnalytics.totalInventoryValue.toFixed(2)},${currency}\n`;
    csv += `Total Stock Units on Hand,${comprehensiveAnalytics.totalUnitsOnHand},Units\n`;
    csv += `Stock Turnover Ratio,${comprehensiveAnalytics.overallTurnoverRatio.toFixed(2)},x / period\n`;
    csv += `Sell-Through Rate (STR),${comprehensiveAnalytics.overallSellThroughRate.toFixed(1)},%\n`;
    csv += `Order Fill Rate (OTIF),${comprehensiveAnalytics.orderFillRate.toFixed(1)},%\n`;
    csv += `Active Out-of-Stock Items,${comprehensiveAnalytics.activeStockouts},Items\n`;
    csv += `Dead / Stagnant Stock Capital,${comprehensiveAnalytics.deadStockValue.toFixed(2)},${currency}\n\n`;

    csv += `CATEGORY DISTRIBUTION & CAPITAL BREAKDOWN\n`;
    csv += `Category Name,Holding Value (${currency}),Units on Hand,Capital Share (%)\n`;
    comprehensiveAnalytics.categoryDistribution.forEach(cat => {
      csv += `"${cat.name}",${cat.value.toFixed(2)},${cat.units},${cat.percent.toFixed(1)}%\n`;
    });
    csv += `\n`;

    csv += `STOCK MOVEMENT VELOCITY PROFILE\n`;
    csv += `Velocity Segment,Units,Capital Valuation (${currency}),Percentage Share\n`;
    comprehensiveAnalytics.movementDistribution.forEach(mv => {
      csv += `"${mv.name}",${mv.units},${mv.value.toFixed(2)},${mv.percent.toFixed(1)}%\n`;
    });
    csv += `\n`;

    csv += `TOP TIED-UP CAPITAL PRODUCTS\n`;
    csv += `Product Name,Stock Units,Unit Price (${currency}),Total Tied-Up Cash (${currency})\n`;
    comprehensiveAnalytics.tiedUpCapitalData.slice(0, 15).forEach(item => {
      csv += `"${item.name.replace(/"/g, '""')}",${item.quantity},${item.price.toFixed(2)},${item.tiedUpCapital.toFixed(2)}\n`;
    });

    downloadFile('\uFEFF' + csv, `Invenio_Executive_Analytics_${selectedPeriod.replace(/\s+/g, '_')}_${dateStr}.csv`, 'text/csv;charset=utf-8;');
    showToast('Executive Summary CSV downloaded successfully!');
  };

  const handleExportProductLedgerCSV = () => {
    const dateStr = new Date().toISOString().split('T')[0];
    let csv = `SKU,Product Name,Category,Current Stock,Unit Cost (${currency}),Selling Price (${currency}),Total Valuation (${currency}),Units Sold,Beginning Stock,Ending Stock,Average Stock,COGS (${currency}),Turnover Ratio,Movement Velocity\n`;

    filteredProductsStats.forEach(stat => {
      const cleanName = (stat.name || '').replace(/"/g, '""');
      const cleanSKU = (stat.sku || '').replace(/"/g, '""');
      const cleanCat = (stat.category || 'General').replace(/"/g, '""');
      const totalVal = (stat.currentStock * stat.costPrice).toFixed(2);

      csv += `"${cleanSKU}","${cleanName}","${cleanCat}",${stat.currentStock},${stat.costPrice.toFixed(2)},${stat.sellingPrice.toFixed(2)},${totalVal},${stat.unitsSold},${stat.beginningStock},${stat.endingStock},${stat.averageStock},${stat.cogs.toFixed(2)},${stat.turnoverRatio.toFixed(2)}x,"${stat.speed}"\n`;
    });

    downloadFile('\uFEFF' + csv, `Invenio_Product_Velocity_Ledger_${dateStr}.csv`, 'text/csv;charset=utf-8;');
    showToast('Product Velocity Ledger CSV downloaded successfully!');
  };

  const handleExportJSON = () => {
    const dateStr = new Date().toISOString().split('T')[0];
    const exportPayload = {
      metadata: {
        workspace: company?.name || 'Invenio',
        currency: currency,
        period: selectedPeriod,
        exportedAt: new Date().toISOString(),
        exportedBy: profile?.name || user?.email || 'User',
      },
      executiveSummary: comprehensiveAnalytics,
      productsVelocity: filteredProductsStats,
    };

    const jsonStr = JSON.stringify(exportPayload, null, 2);
    downloadFile(jsonStr, `Invenio_Analytics_Payload_${dateStr}.json`, 'application/json;charset=utf-8;');
    showToast('Raw Analytics JSON exported successfully!');
  };

  const handlePrintReport = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('Pop-up blocked. Please allow pop-ups for this site to generate printable reports.');
      return;
    }

    const companyName = company?.name || 'Invenio Inventory';
    const reportDate = new Date().toLocaleDateString('en-US', { dateStyle: 'full' });

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Executive Inventory Analytics - ${companyName}</title>
        <style>
          * { box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; }
          body { padding: 40px; color: #0f172a; max-width: 1000px; margin: 0 auto; background: #fff; }
          .header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #0f172a; padding-bottom: 20px; margin-bottom: 28px; }
          .title { font-size: 24px; font-weight: 900; margin: 0; color: #0f172a; text-transform: uppercase; letter-spacing: -0.5px; }
          .subtitle { font-size: 13px; color: #64748b; margin-top: 4px; font-weight: 600; }
          .meta { text-align: right; font-size: 12px; color: #475569; }
          .grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin-bottom: 30px; }
          .card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 16px; }
          .card-label { font-size: 11px; font-weight: 700; color: #64748b; text-transform: uppercase; letter-spacing: 0.5px; }
          .card-val { font-size: 20px; font-weight: 900; color: #0f172a; margin-top: 6px; }
          .card-sub { font-size: 10px; color: #10b981; font-weight: 700; margin-top: 4px; }
          h2 { font-size: 16px; font-weight: 800; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px; margin-top: 32px; margin-bottom: 16px; color: #1e293b; text-transform: uppercase; }
          table { width: 100%; border-collapse: collapse; margin-bottom: 24px; font-size: 12px; }
          th { text-align: left; padding: 10px 12px; background: #f1f5f9; color: #334155; font-weight: 800; border-bottom: 2px solid #cbd5e1; text-transform: uppercase; font-size: 10px; }
          td { padding: 10px 12px; border-bottom: 1px solid #e2e8f0; color: #334155; }
          tr:nth-child(even) { background-color: #f8fafc; }
          .text-right { text-align: right; }
          .badge { display: inline-block; padding: 3px 8px; font-size: 10px; font-weight: 800; border-radius: 6px; text-transform: uppercase; }
          .badge-fast { background: #dcfce7; color: #15803d; }
          .badge-slow { background: #fef3c7; color: #b45309; }
          .badge-dead { background: #fee2e2; color: #b91c1c; }
          .footer { margin-top: 48px; border-top: 1px dashed #cbd5e1; padding-top: 20px; display: flex; justify-content: space-between; font-size: 11px; color: #94a3b8; }
          @media print {
            body { padding: 0; }
            .no-print { display: none; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <h1 class="title">${companyName}</h1>
            <p class="subtitle">Executive Inventory & Financial Analytics Report</p>
          </div>
          <div class="meta">
            <p><strong>Period:</strong> ${selectedPeriod}</p>
            <p><strong>Date:</strong> ${reportDate}</p>
            <p><strong>Prepared by:</strong> ${profile?.name || user?.email || 'Operations'}</p>
          </div>
        </div>

        <div class="grid">
          <div class="card">
            <div class="card-label">Total Revenue</div>
            <div class="card-val">${currency}${comprehensiveAnalytics.revenue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</div>
            <div class="card-sub">Margin: ${comprehensiveAnalytics.grossProfitMargin.toFixed(1)}%</div>
          </div>
          <div class="card">
            <div class="card-label">Gross Profit</div>
            <div class="card-val">${currency}${comprehensiveAnalytics.grossProfit.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</div>
            <div class="card-sub">Net Est: ${currency}${comprehensiveAnalytics.netProfit.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</div>
          </div>
          <div class="card">
            <div class="card-label">Inventory Valuation</div>
            <div class="card-val">${currency}${comprehensiveAnalytics.totalInventoryValue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</div>
            <div class="card-sub" style="color: #64748b;">${comprehensiveAnalytics.totalUnitsOnHand.toLocaleString()} units on hand</div>
          </div>
          <div class="card">
            <div class="card-label">Sell-Through Rate</div>
            <div class="card-val">${comprehensiveAnalytics.overallSellThroughRate.toFixed(1)}%</div>
            <div class="card-sub">Turnover: ${comprehensiveAnalytics.overallTurnoverRatio.toFixed(2)}x</div>
          </div>
        </div>

        <h2>Category Performance & Capital Distribution</h2>
        <table>
          <thead>
            <tr>
              <th>Category</th>
              <th class="text-right">Holding Value</th>
              <th class="text-right">Units on Hand</th>
              <th class="text-right">Capital Share</th>
            </tr>
          </thead>
          <tbody>
            ${comprehensiveAnalytics.categoryDistribution.map(cat => `
              <tr>
                <td><strong>${cat.name}</strong></td>
                <td class="text-right">${currency}${cat.value.toLocaleString(undefined, { minimumFractionDigits: 2 })}</td>
                <td class="text-right">${cat.units.toLocaleString()}</td>
                <td class="text-right">${cat.percent.toFixed(1)}%</td>
              </tr>
            `).join('')}
          </tbody>
        </table>

        <h2>Top Tied-Up Capital Products</h2>
        <table>
          <thead>
            <tr>
              <th>Product Name</th>
              <th class="text-right">Stock</th>
              <th class="text-right">Unit Price</th>
              <th class="text-right">Tied-Up Capital</th>
            </tr>
          </thead>
          <tbody>
            ${comprehensiveAnalytics.tiedUpCapitalData.slice(0, 10).map(item => `
              <tr>
                <td><strong>${item.name}</strong></td>
                <td class="text-right">${item.quantity}</td>
                <td class="text-right">${currency}${item.price.toFixed(2)}</td>
                <td class="text-right"><strong>${currency}${item.tiedUpCapital.toLocaleString(undefined, { minimumFractionDigits: 2 })}</strong></td>
              </tr>
            `).join('')}
          </tbody>
        </table>

        <h2>Product Turnover Velocity Matrix</h2>
        <table>
          <thead>
            <tr>
              <th>SKU / Product</th>
              <th>Category</th>
              <th class="text-right">Stock</th>
              <th class="text-right">Units Sold</th>
              <th class="text-right">COGS</th>
              <th class="text-right">Turnover</th>
              <th class="text-right">Speed</th>
            </tr>
          </thead>
          <tbody>
            ${filteredProductsStats.slice(0, 15).map(p => `
              <tr>
                <td><strong>${p.name}</strong><br><span style="font-size: 10px; color: #94a3b8;">${p.sku || 'N/A'}</span></td>
                <td>${p.category}</td>
                <td class="text-right">${p.currentStock}</td>
                <td class="text-right">${p.unitsSold}</td>
                <td class="text-right">${currency}${p.cogs.toLocaleString()}</td>
                <td class="text-right"><strong>${p.turnoverRatio.toFixed(2)}x</strong></td>
                <td class="text-right"><span class="badge ${p.speed === 'Fast' ? 'badge-fast' : p.speed === 'Slow' ? 'badge-slow' : 'badge-dead'}">${p.speed}</span></td>
              </tr>
            `).join('')}
          </tbody>
        </table>

        <div class="footer">
          <span>Invenio Business Intelligence Platform</span>
          <span>Confidential — For Internal Management Use Only</span>
        </div>

        <script>
          window.onload = function() {
            setTimeout(function() {
              window.print();
            }, 500);
          };
        </script>
      </body>
      </html>
    `;

    printWindow.document.open();
    printWindow.document.write(html);
    printWindow.document.close();
    showToast('Print dialog opened for executive report!');
  };

  useEffect(() => {
    if (!profile?.companyId) return;

    const prodQuery = collection(db, `companies/${profile.companyId}/products`);
    const unsubscribeProducts = onSnapshot(prodQuery, (snapshot) => {
      setProducts(snapshot.docs.map(doc => {
        const data = doc.data() as any;
        return {
          ...data,
          id: doc.id,
          movement: getProductMovementSpeed(data)
        };
      }));
      setProductsLoaded(true);
    }, (error) => {
      console.error("Query error in Analytics products:", error);
      setProductsLoaded(true);
    });

    const movQuery = collection(db, `companies/${profile.companyId}/stockMovements`);
    const unsubscribeMovements = onSnapshot(movQuery, (snapshot) => {
      setStockMovements(snapshot.docs.map(doc => ({
        id: doc.id,
        ...doc.data()
      })));
      setMovementsLoaded(true);
    }, (error) => {
      console.error("Query error in Analytics movements:", error);
      setMovementsLoaded(true);
    });

    const invQuery = collection(db, `companies/${profile.companyId}/invoices`);
    const unsubscribeInvoices = onSnapshot(invQuery, (snapshot) => {
      setInvoices(snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id })));
      setInvoicesLoaded(true);
    }, (error) => {
      console.error("Query error in Analytics invoices:", error);
      setInvoicesLoaded(true);
    });

    return () => {
      unsubscribeProducts();
      unsubscribeMovements();
      unsubscribeInvoices();
    };
  }, [profile?.companyId]);

  const loading = !productsLoaded || !movementsLoaded || !invoicesLoaded;

  // Custom range memo
  const customRange = useMemo(() => {
    if (!customStartDate || !customEndDate) return undefined;
    return {
      start: new Date(customStartDate + 'T00:00:00'),
      end: new Date(customEndDate + 'T23:59:59')
    };
  }, [customStartDate, customEndDate]);

  // Date range memo
  const dateRange = useMemo(() => {
    return getDateRangeForPeriod(selectedPeriod, customRange);
  }, [selectedPeriod, customRange]);

  // Comprehensive Analytics Calculation Engine (Single Source of Truth)
  const comprehensiveAnalytics = useMemo(() => {
    return calculateComprehensiveAnalytics(
      products,
      invoices,
      stockMovements,
      selectedPeriod,
      customRange,
      currency
    );
  }, [products, invoices, stockMovements, selectedPeriod, customRange, currency]);

  // Overall statistics memo
  const overallStats = useMemo(() => {
    return calculateStockTurnover(products, stockMovements, dateRange);
  }, [products, stockMovements, dateRange]);

  // Turnover Trend (Line Chart) data
  const turnoverRatioData = useMemo(() => {
    return calculateMonthlyTurnoverTrend(products, stockMovements);
  }, [products, stockMovements]);

  // Dynamic Metrics Calculation
  const allProducts = [...products];
  
  const totalCapital = allProducts.reduce((sum, p) => sum + ((p.value || p.buyingPrice || 0) * (p.quantity || 0)), 0);
  const totalSKUs = allProducts.length;

  const totalUnitsSold = allProducts.reduce((sum, p) => sum + (p.unitsSold || 0), 0);
  const totalUnitsReceived = allProducts.reduce((sum, p) => {
    const received = typeof p.unitsReceived === 'number' && p.unitsReceived > 0
      ? p.unitsReceived 
      : p.quantity + (p.unitsSold || 0);
    return sum + received;
  }, 0);
  const averageSTR = totalUnitsReceived > 0 ? (totalUnitsSold / totalUnitsReceived) * 100 : 0;

  // Calculate Sales, Gross Profit, and Net Profit from Invoices
  const salesMetrics = useMemo(() => {
    const salesInvoices = invoices.filter(inv => inv.type === 'standard' || !inv.type);
    
    const filteredInvoices = salesInvoices.filter(inv => {
      const invDateStr = inv.date || inv.createdAt;
      if (!invDateStr) return true;
      const invDate = new Date(invDateStr);
      if (isNaN(invDate.getTime())) return true;
      if (dateRange?.start && invDate < dateRange.start) return false;
      if (dateRange?.end && invDate > dateRange.end) return false;
      return true;
    });

    let totalSales = 0;
    let totalCOGS = 0;

    filteredInvoices.forEach(inv => {
      const items = inv.items || [];
      if (items.length === 0) {
        const amt = Number(inv.amount) || 0;
        totalSales += amt;
        totalCOGS += amt * 0.65;
      } else {
        items.forEach((it: any) => {
          const qty = Number(it.quantity) || 1;
          const price = Number(it.price || it.unitPrice) || 0;
          const lineTotal = Number(it.total) || qty * price;
          totalSales += lineTotal;

          const prod = products.find(p => p.id === it.productId || p.sku === it.sku || p.name === it.name);
          let unitCost = Number(prod?.buyingPrice || prod?.value || it.buyingPrice || it.cost || 0);
          if (unitCost <= 0) {
            unitCost = price > 0 ? price * 0.65 : lineTotal * 0.65;
          }
          totalCOGS += qty * unitCost;
        });
      }
    });

    const grossProfit = totalSales - totalCOGS;
    const operatingExpenses = Math.round(totalSales * 0.12);
    const netProfit = grossProfit - operatingExpenses;

    return { totalSales, grossProfit, netProfit };
  }, [invoices, products, dateRange]);

  // Overall/Average Turnover value for the stat card
  const overallTurnover = overallStats.overallRatio;
  
  const categoryStats = allProducts.reduce((acc: any[], p) => {
    const existing = acc.find(c => c.name === p.category);
    const val = (p.value || p.buyingPrice || 0) * (p.quantity || 0);
    if (existing) {
      existing.value += val;
    } else {
      acc.push({ 
        id: acc.length + 1, 
        name: p.category || 'Uncategorized', 
        value: val, 
        color: COLORS[acc.length % COLORS.length] 
      });
    }
    return acc;
  }, []).sort((a, b) => b.value - a.value);

  const categoriesList = useMemo(() => {
    const list = new Set<string>();
    products.forEach(p => {
      if (p.category) list.add(p.category);
    });
    return ['All', ...Array.from(list)];
  }, [products]);

  const filteredProductsStats = useMemo(() => {
    return overallStats.productsStats.filter(stat => {
      const matchesSearch = stat.productName.toLowerCase().includes(searchQuery.toLowerCase()) || 
                            stat.sku.toLowerCase().includes(searchQuery.toLowerCase());
      const matchesCategory = selectedCategory === 'All' || stat.category === selectedCategory;
      return matchesSearch && matchesCategory;
    });
  }, [overallStats.productsStats, searchQuery, selectedCategory]);

  const movementDataMap = allProducts.reduce((acc, p) => {
    let key = p.movement || 'slow';
    
    if (!acc[key]) acc[key] = { value: 0, items: 0 };
    acc[key].value += (p.value || p.buyingPrice || 0) * (p.quantity || 0);
    acc[key].items += p.quantity; // Summing quantities as requested
    return acc;
  }, {} as any);

  const MOVEMENT_DATA = [
    { name: 'Fast Moving', key: 'fast', color: 'bg-blue-500', icon: TrendingUp, desc: 'High demand, maintain stock' },
    { name: 'Moderate', key: 'moderate', color: 'bg-emerald-500', icon: Activity, desc: 'Steady sales, monitor trends' },
    { name: 'Slow Moving', key: 'slow', color: 'bg-amber-500', icon: Clock, desc: 'Consider discounts' },
    { name: 'Obsolete', key: 'obsolete', color: 'bg-rose-500', icon: Ban, desc: 'Liquidate or clear' },
  ].map(m => {
    const data = movementDataMap[m.key] || { value: 0, items: 0 };
    return {
      ...m,
      value: data.value,
      items: data.items,
      percentage: totalCapital > 0 ? Math.round((data.value / totalCapital) * 100) : 0
    };
  });

  // ABC Analysis (70/20/10 rule simulation based on value density)
  const sortedByValue = [...allProducts].sort((a, b) => (b.value * b.quantity) - (a.value * a.quantity));

  let cumulativeValue = 0;
  const abcAnalysis = [
    { class: 'A', limit: 0.7, items: [] as any[], val: 0, color: 'bg-emerald-500', desc: 'High-value items requiring tight control.' },
    { class: 'B', limit: 0.9, items: [] as any[], val: 0, color: 'bg-blue-500', desc: 'Medium-value items. Balance control and efficiency.' },
    { class: 'C', limit: 1.0, items: [] as any[], val: 0, color: 'bg-slate-400', desc: 'Low-value items. Simplify ordering processes.' },
  ];

  sortedByValue.forEach(p => {
    const pVal = p.value * p.quantity;
    cumulativeValue += pVal;
    const ratio = totalCapital > 0 ? cumulativeValue / totalCapital : 1;
    if (ratio <= 0.7) {
      abcAnalysis[0].items.push(p);
      abcAnalysis[0].val += pVal;
    } else if (ratio <= 0.9) {
      abcAnalysis[1].items.push(p);
      abcAnalysis[1].val += pVal;
    } else {
      abcAnalysis[2].items.push(p);
      abcAnalysis[2].val += pVal;
    }
  });

  return (
    <div className="space-y-6 sm:space-y-8 animate-in fade-in duration-500 pb-20">
      {/* Header & Date Filtering Toolbar */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 text-left">
        <div>
          <h2 className="text-xl sm:text-2xl font-extrabold text-slate-900 tracking-tight">
            Analytics
          </h2>
          <p className="text-slate-500 text-[11px] sm:text-sm font-medium mt-1">
            Real-time business performance, sell-through rate, fill rate, inventory velocity, and financial health
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-3">
          {/* Period selector pills */}
          <div className="flex flex-wrap items-center gap-1 bg-slate-100 p-1 rounded-xl border border-slate-200">
            {(['Today', 'This Week', 'This Month', 'This Year', 'Custom'] as TimePeriod[]).map((period) => (
              <button
                key={period}
                type="button"
                onClick={() => setSelectedPeriod(period)}
                className={cn(
                  "px-3 py-1.5 text-[10px] sm:text-xs font-bold rounded-lg transition-all",
                  selectedPeriod === period
                    ? "bg-white text-slate-950 shadow-xs"
                    : "text-slate-500 hover:text-slate-900"
                )}
              >
                {period}
              </button>
            ))}
          </div>

          {/* Custom Date Picker Fields */}
          {selectedPeriod === 'Custom' && (
            <div className="flex items-center gap-2 bg-white p-1 rounded-xl border border-slate-200 shadow-xs animate-in fade-in slide-in-from-top-1 duration-150">
              <input
                type="date"
                value={customStartDate}
                onChange={(e) => setCustomStartDate(e.target.value)}
                className="px-2 py-1 text-xs font-bold text-slate-700 bg-transparent border-0 outline-none focus:ring-0 cursor-pointer"
              />
              <span className="text-slate-400 text-[10px] font-black uppercase">to</span>
              <input
                type="date"
                value={customEndDate}
                onChange={(e) => setCustomEndDate(e.target.value)}
                className="px-2 py-1 text-xs font-bold text-slate-700 bg-transparent border-0 outline-none focus:ring-0 cursor-pointer"
              />
            </div>
          )}

          <button 
            type="button"
            onClick={() => {
              setProductsLoaded(false);
              setMovementsLoaded(false);
              setInvoicesLoaded(false);
            }}
            className="flex items-center gap-2 px-3 sm:px-4 h-9 sm:h-10 border border-slate-200 rounded-xl bg-white text-slate-700 font-bold hover:bg-slate-50 transition-all text-[10px] sm:text-xs shrink-0 cursor-pointer"
          >
            <RotateCcw className="w-3.5 h-3.5 sm:w-4 sm:h-4 text-slate-400" />
            <span className="truncate">Refresh</span>
          </button>
          <button 
            type="button"
            onClick={() => setShowExportModal(true)}
            className="flex items-center gap-2 bg-[#0f172a] text-white px-3 sm:px-5 h-9 sm:h-10 rounded-xl font-bold hover:bg-slate-800 active:scale-95 transition-all text-[10px] sm:text-xs shrink-0 cursor-pointer shadow-xs"
          >
            <FileDown className="w-3.5 h-3.5 sm:w-4 sm:h-4 text-blue-400" />
            <span className="truncate">Export Report</span>
          </button>
        </div>
      </div>

      {/* 1. EXECUTIVE BUSINESS OWNER "AT A GLANCE" KPI SECTION */}
      <BusinessOwnerKPISection 
        analytics={comprehensiveAnalytics} 
        currency={currency} 
        selectedPeriod={selectedPeriod} 
      />

      {/* 2. SELL-THROUGH RATE (STR) & ORDER FILL RATE (OTIF) SECTION */}
      <SellThroughAndFillRateSection
        analytics={comprehensiveAnalytics}
        products={allProducts}
        currency={currency}
        selectedPeriod={selectedPeriod}
      />

      {/* 3. DYNAMIC ACTIONABLE INSIGHTS SECTION */}
      <InsightBadge
        elementId="analytics_turnover_efficiency"
        variant="banner"
        className="w-full"
      />

      <ActionableInsightsSection 
        insights={comprehensiveAnalytics.actionableInsights} 
      />

      {/* 3. SALES PERFORMANCE TRAJECTORY & STOCK TURNOVER TREND */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 min-w-0">
        {/* Interactive Sales Performance Trend */}
        <SalesPerformanceTrend 
          analytics={comprehensiveAnalytics} 
          currency={currency} 
        />

        {/* Preserved Line Chart: Stock Turnover Trend */}
        <div className="bg-white p-4 sm:p-6 md:p-8 rounded-2xl border border-slate-200 shadow-sm text-left flex flex-col justify-between min-w-0 w-full">
          <div>
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-2">
              <div>
                <h3 className="text-base sm:text-lg font-extrabold text-slate-900">Stock Turnover Trend</h3>
                <p className="text-xs font-medium text-slate-400 mt-0.5">Monthly turnover ratio (Line Chart)</p>
              </div>
              <div className="inline-flex items-center gap-1.5 px-2.5 py-1 bg-blue-50 border border-blue-100 rounded-lg text-blue-700 text-xs font-bold w-fit shrink-0">
                <span className="w-2 h-2 rounded-full bg-blue-500 animate-pulse" />
                {overallTurnover.toFixed(2)}x Current Rate
              </div>
            </div>
            <div className="h-[240px] sm:h-[280px] md:h-[300px] w-full min-h-[200px] min-w-0 mt-4">
              <ResponsiveContainer width="100%" height="100%" minWidth={100} minHeight={200}>
                <LineChart data={turnoverRatioData} margin={{ top: 10, right: 12, left: -14, bottom: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                  <XAxis 
                    dataKey="name" 
                    axisLine={false} 
                    tickLine={false} 
                    tick={{ fontSize: 10, fontWeight: 700, fill: '#64748b' }} 
                    dy={10} 
                    interval={0}
                  />
                  <YAxis 
                    axisLine={false} 
                    tickLine={false} 
                    width={36}
                    tick={{ fontSize: 10, fontWeight: 700, fill: '#64748b' }}
                    tickFormatter={(val) => `${val}x`}
                    domain={[0, 'auto']}
                  />
                  <Tooltip 
                    formatter={(val: any) => [`${Number(val).toFixed(2)}x`, "Turnover Rate"]}
                    contentStyle={{ backgroundColor: '#fff', borderRadius: '12px', border: '1px solid #e2e8f0', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }} 
                    labelStyle={{ fontWeight: 800, color: '#0f172a', marginBottom: '4px' }}
                  />
                  <Legend iconType="circle" wrapperStyle={{ fontSize: '11px', paddingTop: '10px' }} />
                  <Line 
                    type="monotone" 
                    dataKey="turnover" 
                    name="Turnover Rate" 
                    stroke="#3b82f6" 
                    strokeWidth={3} 
                    dot={{ r: 4, fill: '#3b82f6', stroke: '#fff', strokeWidth: 2 }} 
                    activeDot={{ r: 6, fill: '#3b82f6', stroke: '#fff', strokeWidth: 2 }} 
                  />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </div>

          <div className="grid grid-cols-3 gap-2 pt-3 mt-4 border-t border-slate-100 text-center">
            <div className="text-left">
              <span className="block text-[10px] font-bold text-slate-400 uppercase tracking-tight">6-Mo Avg</span>
              <span className="text-xs sm:text-sm font-extrabold text-slate-900">
                {(turnoverRatioData.reduce((s, i) => s + i.turnover, 0) / Math.max(1, turnoverRatioData.length)).toFixed(2)}x
              </span>
            </div>
            <div>
              <span className="block text-[10px] font-bold text-slate-400 uppercase tracking-tight">Peak Month</span>
              <span className="text-xs sm:text-sm font-extrabold text-slate-900">
                {Math.max(...turnoverRatioData.map(i => i.turnover), 0).toFixed(2)}x
              </span>
            </div>
            <div className="text-right">
              <span className="block text-[10px] font-bold text-slate-400 uppercase tracking-tight">Status</span>
              <span className="text-xs sm:text-sm font-extrabold text-emerald-600">
                Active
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* 4. INVENTORY HEALTH OVERVIEW & RISK BREAKDOWN */}
      <InventoryHealthOverview 
        analytics={comprehensiveAnalytics} 
        currency={currency} 
      />

      {/* 5. TOP PRODUCTS (4 PERSPECTIVES) & CATEGORY DISTRIBUTION */}
      <InsightBadge
        elementId="analytics_sell_through"
        variant="banner"
        className="w-full"
      />

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 min-w-0">
        {/* Top Products in 4 Distinct Perspectives */}
        <TopProductsAnalytics 
          analytics={comprehensiveAnalytics} 
          currency={currency} 
        />

        {/* Preserved Pie Chart: Cash Tied by Category */}
        <div className="bg-white p-4 sm:p-6 md:p-8 rounded-2xl border border-slate-200 shadow-sm flex flex-col text-left min-w-0 w-full">
          <div className="mb-6">
            <h3 className="text-xl font-extrabold text-slate-900">Category Distribution</h3>
            <p className="text-xs font-medium text-slate-400 mt-0.5">Inventory value share (Pie Chart)</p>
          </div>
          <div className="flex-1 flex flex-col sm:flex-row items-center sm:justify-between gap-8 py-2">
            <div className="relative w-44 h-44 shrink-0">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={categoryStats.length > 0 ? categoryStats : [{ name: 'No Data', value: 1, color: '#f1f5f9' }]}
                    innerRadius={65}
                    outerRadius={85}
                    paddingAngle={5}
                    dataKey="value"
                    stroke="none"
                  >
                    {categoryStats.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip 
                    formatter={(value: number) => [`${currency}${value.toLocaleString()}`, 'Value']}
                    contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1)' }}
                  />
                </PieChart>
              </ResponsiveContainer>
              <div className="absolute inset-0 flex flex-col items-center justify-center">
                <p className="text-[10px] font-bold text-slate-400 tracking-widest uppercase">Value</p>
                <p className="text-xl font-black text-slate-900 leading-none mt-1">
                  {currency}{totalCapital >= 1000000 
                    ? `${(totalCapital / 1000000).toFixed(1)}M` 
                    : totalCapital.toLocaleString()}
                </p>
              </div>
            </div>
            <div className="flex-1 w-full space-y-3 min-w-[200px]">
              {categoryStats.slice(0, 5).map((cat) => (
                <div key={cat.id} className="flex items-center justify-between group">
                  <div className="flex items-center gap-3 text-left">
                    <div className="w-2.5 h-2.5 rounded-full shrink-0" style={{ backgroundColor: cat.color }} />
                    <span className="text-[11px] font-bold text-slate-500 group-hover:text-slate-900 transition-colors uppercase tracking-tight truncate max-w-[100px]">{cat.name}</span>
                  </div>
                  <span className="text-[11px] font-black text-slate-900">{formatCompactNumber(cat.value, currency)}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* 6. ESTIMATED STOCKOUT HORIZON & REORDER OPPORTUNITIES ("REORDER NOW") */}
      <ReorderStockoutIntelligence 
        analytics={comprehensiveAnalytics} 
        currency={currency} 
      />

      {/* 7. PRESERVED MOVEMENT & VALUE CHARTS */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 min-w-0">
        {/* Column Chart: Movement by Item Count */}
        <div className="bg-white p-6 md:p-8 rounded-2xl border border-slate-200 shadow-sm text-left">
          <div className="mb-6">
            <h3 className="text-lg font-extrabold text-slate-900">Inventory Movement</h3>
            <p className="text-xs font-medium text-slate-400 mt-0.5">Items per movement category (Column Chart)</p>
          </div>
          <div className="h-[300px] w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={MOVEMENT_DATA}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                <XAxis 
                  dataKey="name" 
                  axisLine={false} 
                  tickLine={false} 
                  tick={{ fontSize: 9, fontWeight: 700, fill: '#64748b' }}
                />
                <YAxis 
                  axisLine={false} 
                  tickLine={false} 
                  tick={{ fontSize: 10, fontWeight: 700, fill: '#64748b' }}
                />
                <Tooltip 
                  cursor={{ fill: '#f8fafc' }}
                  contentStyle={{ backgroundColor: '#fff', borderRadius: '12px', border: '1px solid #e2e8f0' }}
                />
                <Bar dataKey="items" name="Total Units" radius={[6, 6, 0, 0]}>
                  {MOVEMENT_DATA.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.color.includes('blue') ? '#3b82f6' : entry.color.includes('emerald') ? '#10b981' : entry.color.includes('amber') ? '#f59e0b' : '#f43f5e'} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Horizontal Bar Chart: Value by Category */}
        <div className="bg-white p-6 md:p-8 rounded-2xl border border-slate-200 shadow-sm text-left">
          <div className="mb-6">
            <h3 className="text-lg font-extrabold text-slate-900">Value Ranking</h3>
            <p className="text-xs font-medium text-slate-400 mt-0.5">Top categories by total value (Bar Chart)</p>
          </div>
          <div className="h-[300px] w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart layout="vertical" data={categoryStats.slice(0, 6)} margin={{ left: 20 }}>
                <CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#f1f5f9" />
                <XAxis type="number" axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: '#64748b' }} hide />
                <YAxis 
                  dataKey="name" 
                  type="category" 
                  axisLine={false} 
                  tickLine={false} 
                  tick={{ fontSize: 11, fontWeight: 700, fill: '#475569' }} 
                  width={80}
                />
                <Tooltip 
                  cursor={{ fill: '#f8fafc' }}
                  formatter={(val: number) => [`${currency}${val.toLocaleString()}`, 'Value']}
                  contentStyle={{ borderRadius: '12px' }}
                />
                <Bar dataKey="value" fill="#6366f1" radius={[0, 6, 6, 0]} barSize={20} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* 8. CAPITAL CONCENTRATION & TIED UP CAPITAL DIAGNOSTIC */}
      <TiedUpCapitalSection products={allProducts} currency={currency} />

      {/* 9. PRESERVED SKU MOVEMENT CLASSIFICATION & AGING DASHBOARD */}
      <div className="w-full">
        <SKUMovementDashboard 
          products={allProducts} 
          movements={stockMovements} 
          currency={currency} 
        />
      </div>

      {/* 10. PRESERVED ABC ANALYSIS SECTION */}
      <InsightBadge
        elementId="analytics_pareto_distribution"
        variant="banner"
        className="w-full"
      />

      <div className="w-full">
        <ABCAnalysisSection products={allProducts} currency={currency} />
      </div>

      {/* 11. PRESERVED SELL-THROUGH RATE (STR) PERFORMANCE CARD */}
      <div className="bg-white p-6 md:p-8 rounded-2xl border border-slate-200 shadow-sm text-left flex flex-col justify-between">
        <div>
          <div className="flex items-center justify-between mb-6">
            <div>
              <h3 className="text-lg font-extrabold text-slate-900">STR Performance Card</h3>
              <p className="text-xs font-medium text-slate-400 mt-0.5">Percentage of inventory sold compared to received</p>
            </div>
            <span className="text-[10px] font-black text-blue-600 bg-blue-50 px-2 py-1 rounded-md uppercase tracking-widest border border-blue-100/30">
              Formula Match
            </span>
          </div>

          <div className="space-y-5">
            {[...allProducts]
              .map(p => ({
                ...p,
                str: getSellThroughRate(p)
              }))
              .sort((a, b) => b.str - a.str)
              .slice(0, 5)
              .map((p, idx) => (
                <div key={idx} className="space-y-2">
                  <div className="flex items-center justify-between text-xs">
                    <span className="font-bold text-slate-800 truncate max-w-[180px]">{p.name}</span>
                    <span className="font-extrabold text-slate-950 font-mono">{p.str.toFixed(1)}%</span>
                  </div>
                  <div className="w-full h-2 bg-slate-100 rounded-full overflow-hidden">
                    <div 
                      className={cn(
                        "h-full rounded-full transition-all duration-500",
                        p.str >= 70 ? "bg-emerald-500" : p.str >= 40 ? "bg-blue-500" : "bg-amber-500"
                      )}
                      style={{ width: `${Math.min(100, p.str)}%` }}
                    />
                  </div>
                  <div className="flex justify-between items-center text-[10px] font-bold text-slate-400">
                    <span>Sold: {p.unitsSold || 0} units</span>
                    <span>Received: {p.unitsReceived || (p.quantity + (p.unitsSold || 0))} units</span>
                  </div>
                </div>
              ))}
          </div>
        </div>
        <div className="pt-4 mt-6 border-t border-slate-100 text-[10px] font-bold text-slate-400 leading-relaxed">
          Standard Retail Formula: <br />
          <span className="font-mono bg-slate-100/50 px-1.5 py-0.5 rounded text-blue-600 font-extrabold block mt-1 tracking-wide">
            STR = (Units Sold / Units Received) × 100
          </span>
        </div>
      </div>

      {/* 12. PRESERVED PRODUCT-LEVEL STOCK TURNOVER TABLE */}
      <div className="bg-white border border-slate-200 rounded-2xl shadow-sm text-left">
        <div className="p-6 border-b border-slate-100 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h3 className="text-lg font-extrabold text-slate-900">Product Turnover & Inventory Velocity</h3>
            <p className="text-xs font-medium text-slate-400 mt-0.5">
              Ratios computed from real transaction logs for period: <span className="font-bold text-blue-600">{selectedPeriod}</span>
            </p>
          </div>
          <div className="flex flex-col sm:flex-row items-center gap-2">
            {/* Search input */}
            <div className="relative w-full sm:w-60">
              <input
                type="text"
                placeholder="Search name or SKU..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full px-3 py-1.5 pl-8 text-xs font-semibold border border-slate-200 rounded-xl outline-none focus:border-blue-500 transition-colors bg-slate-50/50"
              />
              <svg
                className="absolute left-2.5 top-2.5 w-3.5 h-3.5 text-slate-400"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
              </svg>
            </div>
            
            {/* Category Filter */}
            <select
              value={selectedCategory}
              onChange={(e) => setSelectedCategory(e.target.value)}
              className="w-full sm:w-40 px-3 py-1.5 text-xs font-bold border border-slate-200 rounded-xl outline-none focus:border-blue-500 transition-colors bg-white text-slate-700 cursor-pointer"
            >
              {categoriesList.map(cat => (
                <option key={cat} value={cat}>{cat}</option>
              ))}
            </select>
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse min-w-[700px]">
            <thead>
              <tr className="bg-slate-50/70 border-b border-slate-100 text-[10px] font-bold text-slate-400 uppercase tracking-widest">
                <th className="px-6 py-4">Product Info</th>
                <th className="px-6 py-4">Category</th>
                <th className="px-6 py-4 text-right">Units Sold</th>
                <th className="px-6 py-4 text-right">Beg. Stock</th>
                <th className="px-6 py-4 text-right">End. Stock</th>
                <th className="px-6 py-4 text-right">Avg. Stock</th>
                <th className="px-6 py-4 text-right">COGS</th>
                <th className="px-6 py-4 text-right">Turnover Ratio</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filteredProductsStats.length === 0 ? (
                <tr>
                  <td colSpan={8} className="px-6 py-12 text-center text-slate-400 text-xs font-medium">
                    No matching products found.
                  </td>
                </tr>
              ) : (
                filteredProductsStats.map((stat) => {
                  let speedBadgeColor = "text-amber-600 bg-amber-50 border-amber-100/40";
                  let speedText = "Moderate";
                  if (stat.turnoverRatio >= 4.0) {
                    speedBadgeColor = "text-emerald-600 bg-emerald-50 border-emerald-100/40";
                    speedText = "High Velocity";
                  } else if (stat.turnoverRatio < 1.0) {
                    speedBadgeColor = "text-rose-600 bg-rose-50 border-rose-100/40";
                    speedText = "Slow Velocity";
                  }

                  return (
                    <tr key={stat.productId} className="hover:bg-slate-50/50 transition-colors group">
                      <td className="px-6 py-4">
                        <div className="flex flex-col min-w-0">
                          <span className="text-xs font-bold text-slate-900 group-hover:text-blue-600 transition-colors truncate max-w-[200px]">
                            {stat.productName}
                          </span>
                          <span className="text-[10px] font-mono text-slate-400 mt-0.5">
                            SKU: {stat.sku || 'N/A'}
                          </span>
                        </div>
                      </td>
                      <td className="px-6 py-4">
                        <span className="text-[10px] font-bold text-slate-500 bg-slate-100 px-2.5 py-1 rounded-full uppercase tracking-tight">
                          {stat.category}
                        </span>
                      </td>
                      <td className="px-6 py-4 text-right font-bold text-slate-800 font-mono text-xs">
                        {stat.unitsSold.toLocaleString()}
                      </td>
                      <td className="px-6 py-4 text-right font-medium text-slate-500 font-mono text-xs">
                        {stat.beginningStock.toLocaleString()}
                      </td>
                      <td className="px-6 py-4 text-right font-medium text-slate-500 font-mono text-xs">
                        {stat.endingStock.toLocaleString()}
                      </td>
                      <td className="px-6 py-4 text-right font-medium text-slate-700 font-mono text-xs">
                        {stat.averageStock.toLocaleString()}
                      </td>
                      <td className="px-6 py-4 text-right font-bold text-slate-900 font-mono text-xs">
                        {currency}{stat.cogs.toLocaleString()}
                      </td>
                      <td className="px-6 py-4 text-right">
                        <div className="flex flex-col items-end gap-1.5">
                          <span className="text-xs font-black text-slate-950 font-mono">
                            {stat.turnoverRatio.toFixed(2)}x
                          </span>
                          <span className={cn("text-[8px] font-extrabold uppercase px-1.5 py-0.5 rounded border tracking-wider", speedBadgeColor)}>
                            {speedText}
                          </span>
                        </div>
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
        <div className="p-4 bg-slate-50/50 border-t border-slate-100 flex flex-col sm:flex-row sm:items-center justify-between gap-2 text-[10px] font-bold text-slate-400">
          <span>Showing {filteredProductsStats.length} of {overallStats.productsStats.length} products</span>
          <span className="font-mono text-blue-600 font-black">
            Turnover Ratio = Units Sold (or COGS) ÷ Average Inventory (Quantity or Value)
          </span>
        </div>
      </div>

      {/* Export Report Modal */}
      <AnimatePresence>
        {showExportModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/60 backdrop-blur-xs">
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 10 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 10 }}
              className="bg-white rounded-3xl max-w-xl w-full shadow-2xl border border-slate-200 overflow-hidden text-left"
            >
              {/* Header */}
              <div className="p-6 bg-slate-900 text-white flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-xl bg-blue-600/30 border border-blue-400/30 flex items-center justify-center text-blue-400">
                    <FileDown className="w-5 h-5" />
                  </div>
                  <div>
                    <h3 className="text-base font-black tracking-tight">Export Executive Analytics</h3>
                    <p className="text-xs text-slate-400 font-medium">Select report format for period: <span className="text-blue-400 font-bold">{selectedPeriod}</span></p>
                  </div>
                </div>
                <button
                  onClick={() => setShowExportModal(false)}
                  className="p-2 rounded-xl text-slate-400 hover:text-white hover:bg-slate-800 transition-all cursor-pointer"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              {/* Body Formats */}
              <div className="p-6 space-y-3 bg-slate-50/50">
                {/* 1. Executive Summary CSV */}
                <div className="p-4 bg-white rounded-2xl border border-slate-200 hover:border-blue-400 hover:shadow-md transition-all flex items-center justify-between gap-4 group">
                  <div className="flex items-start gap-3.5">
                    <div className="w-10 h-10 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center shrink-0 mt-0.5 group-hover:scale-105 transition-transform">
                      <FileSpreadsheet className="w-5 h-5" />
                    </div>
                    <div>
                      <h4 className="text-sm font-bold text-slate-900">Executive Summary & KPIs (.CSV)</h4>
                      <p className="text-xs text-slate-500 mt-0.5 leading-relaxed">
                        Comprehensive summary of Revenue, Profit Margins, Stock Turnover, Category allocations, and Tied-Up Capital.
                      </p>
                    </div>
                  </div>
                  <button
                    onClick={() => {
                      handleExportExecutiveSummaryCSV();
                      setShowExportModal(false);
                    }}
                    className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-xs font-bold shrink-0 transition-all flex items-center gap-1.5 shadow-sm shadow-blue-200 cursor-pointer"
                  >
                    <Download className="w-3.5 h-3.5" />
                    <span>Download</span>
                  </button>
                </div>

                {/* 2. Product Velocity Ledger CSV */}
                <div className="p-4 bg-white rounded-2xl border border-slate-200 hover:border-emerald-400 hover:shadow-md transition-all flex items-center justify-between gap-4 group">
                  <div className="flex items-start gap-3.5">
                    <div className="w-10 h-10 rounded-xl bg-emerald-50 text-emerald-600 flex items-center justify-center shrink-0 mt-0.5 group-hover:scale-105 transition-transform">
                      <BarChart3 className="w-5 h-5" />
                    </div>
                    <div>
                      <h4 className="text-sm font-bold text-slate-900">Product Turnover & Velocity Ledger (.CSV)</h4>
                      <p className="text-xs text-slate-500 mt-0.5 leading-relaxed">
                        Itemized SKU ledger showing unit costs, stock valuations, sold units, COGS, turnover ratios, and speed classifications ({filteredProductsStats.length} items).
                      </p>
                    </div>
                  </div>
                  <button
                    onClick={() => {
                      handleExportProductLedgerCSV();
                      setShowExportModal(false);
                    }}
                    className="px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl text-xs font-bold shrink-0 transition-all flex items-center gap-1.5 shadow-sm shadow-emerald-200 cursor-pointer"
                  >
                    <Download className="w-3.5 h-3.5" />
                    <span>Download</span>
                  </button>
                </div>

                {/* 3. Formatted Printable Executive Report */}
                <div className="p-4 bg-white rounded-2xl border border-slate-200 hover:border-indigo-400 hover:shadow-md transition-all flex items-center justify-between gap-4 group">
                  <div className="flex items-start gap-3.5">
                    <div className="w-10 h-10 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center shrink-0 mt-0.5 group-hover:scale-105 transition-transform">
                      <Printer className="w-5 h-5" />
                    </div>
                    <div>
                      <h4 className="text-sm font-bold text-slate-900">Printable Executive Report (PDF / Print)</h4>
                      <p className="text-xs text-slate-500 mt-0.5 leading-relaxed">
                        Styled executive business document ready for board presentation, executive sign-off, or instant PDF printing.
                      </p>
                    </div>
                  </div>
                  <button
                    onClick={() => {
                      handlePrintReport();
                      setShowExportModal(false);
                    }}
                    className="px-4 py-2 bg-slate-900 hover:bg-slate-800 text-white rounded-xl text-xs font-bold shrink-0 transition-all flex items-center gap-1.5 shadow-sm cursor-pointer"
                  >
                    <Printer className="w-3.5 h-3.5" />
                    <span>Print / PDF</span>
                  </button>
                </div>

                {/* 4. Raw JSON Export */}
                <div className="p-4 bg-white rounded-2xl border border-slate-200 hover:border-amber-400 hover:shadow-md transition-all flex items-center justify-between gap-4 group">
                  <div className="flex items-start gap-3.5">
                    <div className="w-10 h-10 rounded-xl bg-amber-50 text-amber-600 flex items-center justify-center shrink-0 mt-0.5 group-hover:scale-105 transition-transform">
                      <Database className="w-5 h-5" />
                    </div>
                    <div>
                      <h4 className="text-sm font-bold text-slate-900">Raw Analytics Snapshot (.JSON)</h4>
                      <p className="text-xs text-slate-500 mt-0.5 leading-relaxed">
                        Complete raw structured payload of all calculated metrics and product velocity data for external ERP/BI ingestion.
                      </p>
                    </div>
                  </div>
                  <button
                    onClick={() => {
                      handleExportJSON();
                      setShowExportModal(false);
                    }}
                    className="px-4 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl text-xs font-bold shrink-0 transition-all flex items-center gap-1.5 cursor-pointer"
                  >
                    <Download className="w-3.5 h-3.5" />
                    <span>JSON</span>
                  </button>
                </div>
              </div>

              {/* Footer */}
              <div className="p-4 bg-white border-t border-slate-100 flex items-center justify-end">
                <button
                  onClick={() => setShowExportModal(false)}
                  className="px-5 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl text-xs font-bold transition-all cursor-pointer"
                >
                  Close
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* Floating Success Toast */}
      <AnimatePresence>
        {exportFeedback && (
          <motion.div
            initial={{ opacity: 0, y: 20, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 20, scale: 0.95 }}
            className="fixed bottom-6 right-6 z-50 bg-slate-900 text-white px-5 py-3.5 rounded-2xl shadow-2xl border border-slate-800 flex items-center gap-3"
          >
            <div className="w-6 h-6 rounded-full bg-emerald-500 text-white flex items-center justify-center shrink-0">
              <Check className="w-3.5 h-3.5" />
            </div>
            <span className="text-xs font-bold">{exportFeedback}</span>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

